[features]
seeds = false
skip-lint = false
[programs.devnet]
solana_nft = "FRp18Tu2U545ztPWqma7uHudGW1eiSLnBdpG2SJjgybR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/ic1993/.config/solana/id.json"

[scripts]
test_mint = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/mint.test.ts"
test_sell = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/sell.test.ts"