[features]
seeds = false
skip-lint = false
[programs.devnet]
solana_nft = "8kbjHeUBCB7p7gXa36aZRqqzW9BNMonTJHxp2tvmccm6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/ic1993/.config/solana/id.json"

[scripts]
MintSellNFT = "yarn run ts-node ./app/main.ts"
test_mint = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/mint.test.ts"
test_sell = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/sell.test.ts"